modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
    modId="shopaholic"
    version="${file.jarVersion}"
    displayName="Shopaholic"
    authors="joshiejack"
    description='''Shops, shipping and gold!'''
[[dependencies.shopaholic]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.shopaholic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.shopaholic]]
    modId="penguinlib"
    mandatory=true
    versionRange="[0.4.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.shopaholic]]
   modId="simplyseasons"
   mandatory=false
   versionRange="[1.16.5-1.0.9,)"
   ordering="AFTER"
   side="BOTH"
